
name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make sheet.pdf
      - uses: actions/upload-artifact@v2
        with: 
          name: sheet.pdf
          path: sheet.pdf

